name: Build and Push Docker image

on:
  push:
    branches:
      - main # ou la branche que vous utilisez

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: |
          ~/.docker/cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/custom-telmi-store:${{ github.sha }} .

    - name: Tag Docker image as latest
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/custom-telmi-store:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/custom-telmi-store:latest

    - name: Verify Docker images
      run: |
        docker images

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/custom-telmi-store:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/custom-telmi-store:latest

    - name: Log out from Docker Hub
      run: docker logout
